[project]
name = "mistralai-gcp"
version = "1.6.0"
description = "Python Client SDK for the Mistral AI API in GCP."
authors = [{ name = "Mistral" }]
requires-python = ">=3.10"
readme = "README.md"
dependencies = [
    "eval-type-backport >=0.2.0",
    "google-auth (>=2.31.0,<3.0.0)",
    "httpx >=0.28.1",
    "pydantic >=2.10.3",
    "python-dateutil >=2.8.2",
    "requests (>=2.32.3,<3.0.0)",
    "typing-inspection >=0.4.0",
]

[dependency-groups]
dev = [
    "mypy==1.14.1",
    "pylint==3.2.3",
    "pyright>=1.1.401,<2",
    "pytest>=8.2.2,<9",
    "pytest-asyncio>=0.23.7,<0.24",
    "types-python-dateutil>=2.9.0.20240316,<3",
]
lint = [
    "ruff>=0.11.10,<0.12",
    "pyright>=1.1.401,<2",
    "mypy==1.15.0",
]

[tool.setuptools.package-data]
"*" = ["py.typed", "src/mistralai_gcp/py.typed"]

[tool.hatch.build.targets.sdist]
include = ["src/mistralai_gcp"]

[tool.hatch.build.targets.sdist.force-include]
"py.typed" = "py.typed"
"src/mistralai_gcp/py.typed" = "src/mistralai_gcp/py.typed"

[tool.hatch.build.targets.wheel]
include = ["src/mistralai_gcp"]

[tool.hatch.build.targets.wheel.sources]
"src/mistralai_gcp" = "mistralai_gcp"

[virtualenvs]
in-project = true

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
pythonpath = ["src"]

[tool.mypy]
disable_error_code = "misc"

[[tool.mypy.overrides]]
module = "typing_inspect"
ignore_missing_imports = true

[[tool.mypy.overrides]]
module = "jsonpath"
ignore_missing_imports = true

[tool.pyright]
venvPath = "."
venv = ".venv"
